server {
    listen <172-31-34-25:8080>;
    listen [::]:<172-31-34-25:8080>;

    server_name <172-31-34-25>;

    root /var/www/devops-hackathon-de008-dangvanluyen/src;
    index index.html;

    access_log /var/log/nginx/<devops-hackathon-de008-dangvanluyen>.access.log;
    error_log /var/log/nginx/<devops-hackathon-de008-dangvanluyen>.error.log;

    location / {
        allow all;
        try_files $uri $uri/ =404;
    }
}